version: "3.9"
services:
  web-server:
    build: .
    ports:
      - "8000:8080"
    environment:
      MONGO_URI: mongodb+srv://wc-bet:QluTYUDcOMkJGQ4N@dev.yvh2sny.mongodb.net/?retryWrites=true&w=majority
      MONGO_DATABASE: wc-bet
      
  